### ISSUE TITLE
can't confirm payment intent when adding payment_consent_id

### ISSUE THREAD

**Issue by leesegundo** [airwallex/airwallex-payment-demo#105]
**Describe the bug** I am trying to make a payment transaction using the customer's existing payment method using consent. I can't confirm payment intent if I add a payment_consent_id instead of element but the confirmPaymentElement() method still looking for the element eventhough I use a payment_consent_id

**To Reproduce**

1. On triggerConfirm() function, update the confirmPaymentIntent to:

confirmPaymentIntent({
    payment_consent_id: 'your_payment_consent_id'
    id: intent_id,
    client_secret,
    },
  })

**Expected behavior** This should confirm the paymentIntent

**Screenshots**
![image](https://github.com/airwallex/airwallex-payment-demo/assets/128762636/b1b16f8f-352f-4d52-83bf-bb17e02cdd93)

**Integration information:**
- language
  - [ ] angular
  - [ ] cdn
  - [ ] node
  - [ ] react
  - [ ] react-ts
  - [ ] ReactNative
  - [*] vue

- element
  - [ ] hpp
  - [ ] dropIn element
  - [ ] card element
  - [*] split card element
  - [ ] full featured card element
  - [ ] applePay element
  - [ ] googlePay element
**Contexts:**
- Browser (e.g. stock browser, safari):
- Language:

**Comment by cowboybkit** [comment]
same on nextjs
Error with prefetch RangeError: Failed to construct 'PaymentRequest': https://google.com/pay payment method identifier violates Content Security Policy.
    at Ue (pay.js:493:409)
    at m.prefetchPaymentData (pay.js:492:201)
    at m.prefetchPaymentData (pay.js:582:235)
    at m.prefetchPaymentData (pay.js:595:885)
    at r.<anonymous> (4907.0f68c1b5.chunk.js:2:7087)
    at Generator.next (<anonymous>)
    at a (4907.0f68c1b5.chunk.js:2:2854)
